version: "3"
services:
  express:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/userservice
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
